# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UkVisaSponsors < Formula
  desc ""
  homepage "https://github.com/renatoaraujo/uk-visa-sponsors"
  version "1.1.4"

  on_macos do
    url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.4/uk-visa-sponsors_1.1.4_darwin_all.tar.gz"
    sha256 "7c5e800b3ebdcbc776d8ad15b556e6b68315a3b29ea9a8e88e4d9827293f4597"

    def install
      bin.install "uk-visa-sponsors"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.4/uk-visa-sponsors_1.1.4_linux_arm64.tar.gz"
      sha256 "5e66126198eb340288e75be4b032ad3ac06b4f88798ca63086a7f8734cd381f7"

      def install
        bin.install "uk-visa-sponsors"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.4/uk-visa-sponsors_1.1.4_linux_amd64.tar.gz"
      sha256 "fa8328817194b09fb7aeccc34422e7f96c639ff785fcabfe5b562d8128cbb906"

      def install
        bin.install "uk-visa-sponsors"
      end
    end
  end
end
