# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ukvisasponsors < Formula
  desc ""
  homepage "https://github.com/renatoaraujo/uk-visa-sponsors"
  version "1.1.2"

  on_macos do
    url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.2/uk-visa-sponsors_1.1.2_darwin_all.tar.gz", using: GitDownloadStrategy
    sha256 "a24b0365a292b0876885038d463ad0fcdb0dbf0623e355b3adb3a1ea91acb83c"

    def install
      bin.install "uk-visa-sponsors"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.2/uk-visa-sponsors_1.1.2_linux_arm64.tar.gz", using: GitDownloadStrategy
      sha256 "f0122a8db829d19b8312a50a6550b7d4e25639657e26f1bea724fe4a42ca0ca8"

      def install
        bin.install "ukvisasponsors"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.2/uk-visa-sponsors_1.1.2_linux_amd64.tar.gz", using: GitDownloadStrategy
      sha256 "0622eb061811d9c27ded4d384d70f70eba3d6c2404dc36ae59b48a33da4d0537"

      def install
        bin.install "ukvisasponsors"
      end
    end
  end
end
