# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ukvisasponsors < Formula
  desc ""
  homepage "https://github.com/renatoaraujo/uk-visa-sponsors"
  version "1.1.1"

  on_macos do
    url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.1/uk-visa-sponsors_1.1.1_darwin_all.tar.gz"
    sha256 "d65d8b13518a9e49087f215e9012bc0cbe56c61c2882dbee9f9428f862f7de6a"

    def install
      bin.install "uk-visa-sponsors"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.1/uk-visa-sponsors_1.1.1_linux_amd64.tar.gz"
      sha256 "e8aaa8967394181543db3d49ad849970cd20635e7daff44a229ae3e2797eed28"

      def install
        bin.install "ukvisasponsors"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.1/uk-visa-sponsors_1.1.1_linux_arm64.tar.gz"
      sha256 "b42ae375057dcc0f7b7b19e4f2e24ee4cc7ba9c939f80db983d1c73f32597a4d"

      def install
        bin.install "ukvisasponsors"
      end
    end
  end
end
