# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ukvisasponsors < Formula
  desc ""
  homepage "https://github.com/renatoaraujo/uk-visa-sponsors"
  version "1.1.3"

  on_macos do
    url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.3/uk-visa-sponsors_1.1.3_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "e495eaef5b1f5dd6dbe230edf33c6127533cff057fa2532998a1bb672ef1ead2"

    def install
      bin.install "uk-visa-sponsors"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.3/uk-visa-sponsors_1.1.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c6d90deca79e819e7388b13d36230be7197a97d3ca2d39edef845b6940ff5ace"

      def install
        bin.install "ukvisasponsors"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/renatoaraujo/uk-visa-sponsors/releases/download/v1.1.3/uk-visa-sponsors_1.1.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d6fd90e9b2db2f243fcef9186645efb81cfaa9c16d67b202db3a8fb14097938a"

      def install
        bin.install "ukvisasponsors"
      end
    end
  end
end
